name: ai-ml-llm-env  # The name of the Conda environment
channels:
  - defaults
  - pytorch  # Add the PyTorch channel
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - gym
  - pip:
    - transformers  # If you're working with LLMs like HuggingFace
    - kaggle
    - pygame